### ISSUE TITLE
Tesseract 3.04?

### ISSUE THREAD

**Issue by sujiewen** [gali8/Tesseract-OCR-iOS#280] opened 2016-08-16 05:11 UTC
Tesseract 3.0.4 When can replace？

**Comment by ljx09195117** [comment] 2016-08-26 08:04
how resolve this problem？

**Comment by ws233** [comment] 2016-09-28 09:52
Duplicate of #277 and #214 
Closing. Feel free to reopen it if you think it's not a duplicate and have extra knowledge about the issue.

**Closed by ws233** 2016-09-28 09:52 UTC
