### ISSUE TITLE
G8Tesseract.mm:pixForImage EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by hydex86** [gali8/Tesseract-OCR-iOS#162] opened 2015-04-03 15:57 UTC
I am trying to capture images with this framework and an iPhone 6 running iOS 8.2. When I try to scan the original image captured from UIImagePickerController:

```
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    chosenImage = info[UIImagePickerControllerOriginalImage];
    [picker dismissViewControllerAnimated:YES completion:NULL];
    [self recognizeImageWithTesseract:chosenImage];
}
```

I got an EXC_BAD_ACCESS in line:

```
data[x] = (pixels[x * 4] << 24) | (pixels[x * 4 + 1] << 16) |
                        (pixels[x * 4 + 2] << 8) | pixels[x * 4 + 3];
```

On this class:

```
G8Tesseract:pixForImage {
...
case 32:
            // Maintain byte order consistency across different endianness.
            for (int y = 0; y < height; ++y, pixels += bytesPerRow, data += wpl) {
                for (int x = 0; x < width; ++x) {
                    data[x] = (pixels[x * 4] << 24) | (pixels[x * 4 + 1] << 16) |
                        (pixels[x * 4 + 2] << 8) | pixels[x * 4 + 3];
                }
            }
            break;
```

**Comment by kevincon** [comment] 2015-04-03 18:07
What version of the library are you using? What does your Podfile look like? Can you post the image that is causing the crash so I can try to reproduce it?

**Comment by johnmillz** [comment] 2015-04-07 13:35
Hi Kevin, I'm seeing the same issue with images captured via AVFoundation captureStillImageAsynchronouslyFromConnection using the rear camera. This method has a completion block that provides the current image buffer, I convert that into a UIImage like so:

                NSData * imageData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:imageDataSampleBuffer];
                UIImage * image = [[UIImage alloc] initWithData:imageData];

**Comment by kevincon** [comment] 2015-04-07 16:00
@johnmillz What version of the library are you using? What does your Podfile look like? The reason I ask is that this may be related to an issue that was resolved in the 4.0.0 release last week.

**Comment by johnmillz** [comment] 2015-04-08 10:28
@kevincon I had the source included from a couple of months ago. Updating to the latest pod resolved the issue for me, runs a treat now. Thanks!

**Comment by kevincon** [comment] 2015-04-08 16:07
I'm glad that resolved it for you. @hydex86 my hope is that updating to the latest version of the library will resolve your errors too. I'll close this issue with that in mind, but feel free to reopen it or start a new issue if you have any more problems.

**Closed by kevincon** 2015-04-08 16:07 UTC

**Comment by hydex86** [comment] 2015-04-08 22:36
@kevincon I updated to latest version and everything works fine. Thank you very much!

**Comment by chenshipeng** [comment] 2017-05-11 09:37
I crashed at [tesseract recognize]; with EXC_BAD_ACCESS.do  you know why?
