### ISSUE TITLE
Bad return code from configEngine on using new .traineddata file

### ISSUE THREAD

**Issue by Xyo** [gali8/Tesseract-OCR-iOS#181] opened 2015-06-02 20:57 UTC
I get EXC_BAD_ACCESS from configEngine when using a new .traineddata file instead of the one included in the english pack. The new trained data file works just fine on PC. Any guidance on this?

**Comment by kevincon** [comment] 2015-06-03 02:49
What version of Tesseract are you running on your PC (What's the output of `tesseract -v`?)? You may be having the same issue this user had (read to the end to see his solution): https://github.com/gali8/Tesseract-OCR-iOS/issues/152

**Comment by Xyo** [comment] 2015-06-03 03:07
I'm using Tesseract 3.02.

**Comment by kevincon** [comment] 2015-06-03 03:18
This iOS library uses Tesseract 3.03-rc1 (see the README). What happens if you try your custom traineddata file after upgrading to the 3.03-rc1 version of Tesseract on your PC? If that still doesn't work, how about if you recreate your custom traineddata file using the 3.03-rc1 version of Tesseract? The two versions may have some incompatibilities. 

The other issue I linked to above (#152) resolved a similar issue by rebundling the latest version of the development version of the Tesseract library (I think it's referred to as 3.04 dev, but it's just the HEAD of the upstream Tesseract repo). 3.04 dev seemed to fix some bugs related to custom traineddata files, so you can try that as well. Perhaps if you contact that user he would be willing to share his fork of this library.

**Comment by Xyo** [comment] 2015-06-04 21:35
I tried it out with a new custom traineddata file created with the 3.03-rc1 version of Tesseract but I get the same error message. I haven't gotten Tesseract 3.04 to compile for me yet so I can't try that out yet.

**Comment by Xyo** [comment] 2015-06-11 13:54
I've tested it out with custom traineddata files created with 3.02, 3.03, and 3.04. All will work with tesseract engine only. Using the cube or combined cube + engine will give the bad access error while running.

**Comment by kevincon** [comment] 2015-06-13 02:48
Ah yes that's a known issue. Long story short, we discovered that cube only works with the eng.traineddata file provided by the upstream Tesseract repository. It doesn't seem to work with other trained data files, both Tesseract-provided and user-created. See: https://github.com/gali8/Tesseract-OCR-iOS/issues/140

**Comment by kevincon** [comment] 2015-06-20 08:06
I believe this is a duplicate of #140, so I'm closing it now, but feel free to reopen it or open a new issue if you need more help.

**Closed by kevincon** 2015-06-20 08:06 UTC
Labels: duplicate
