### ISSUE TITLE
using -weak_library cannot be used with -bitcode_bundle (ENABLE_BITCODE=YES), which is default on in Xcode 7

### ISSUE THREAD

**Issue by tomjtobin** [gali8/Tesseract-OCR-iOS#185] opened 2015-06-19 00:05 UTC
With the Xcode 7, the bitcode options are turned on by default (and mandatory for Watch binaries). Xcode notes that -weak_library can't be used with -bitcode_bundle (link fails).

To get around it, I removed the 
-weak_library /usr/lib/libstdc++.6.0.9.dylib
from the LD flags, and made sure it was using the libstdc++ library in the "c standard library" selection.

The same issue is targeted here: https://github.com/yapstudios/YapDatabase/issues/180 with the note from somebody (albeit unsupported) that you don't need to weak link for iOS7 and above, you can just change the c standard library, and it should be ok.

**Comment by ws233** [comment] 2015-06-19 23:23
Does you approach also work in the old xCode?
In such case can you provide a patch for us?

**Comment by ws233** [comment] 2015-06-20 06:09
@tomjtobin , I've downloaded xCode 7 and couldn't reproduce the issue, you are talking about, on a test or example project. Could you explain more detailed, which test or example projects settings I should change to reproduce the link error?

**Comment by tomjtobin** [comment] 2015-06-20 08:25
Try to archive it.
I created a new project, single view application.
I attached the TesseractOCRiOS pod, v 4.0.0
I reopened the workspace, and changed the view controller to match the sample code at 
https://github.com/gali8/Tesseract-OCR-iOS/wiki/Using-Tesseract-OCR-iOS
Then it can build and run. I was sad, because there was no problem.
Now, try to archive with the iOS device as the target. That fails for me, with the incompatibility warning.
-weak-library seems to come in from PODS_TESSTEST_TESSERACTOCRIOS_OTHER_LDFLAGS which is then inherited by the target project.
You can fix it just by doing this diff (which just removes the -weak-link from the LD flags)
diff --git a/Pods/Target Support Files/Pods-TessTest-TesseractOCRiOS/Pods-TessTest-TesseractOCRiOS.xcconfig b/Pods/Target Support Files/Pods-TessTest-TesseractOCRiOS/Pods-TessTest-TesseractOCRiOS.xcconfig
index b2714fe..fb6e903 100644
--- a/Pods/Target Support Files/Pods-TessTest-TesseractOCRiOS/Pods-TessTest-TesseractOCRiOS.xcconfig    
+++ b/Pods/Target Support Files/Pods-TessTest-TesseractOCRiOS/Pods-TessTest-TesseractOCRiOS.xcconfig    
@@ -1,3 +1,3 @@
 PODS_TESSTEST_TESSERACTOCRIOS_CLANG_CXX_LIBRARY = compiler-default
 PODS_TESSTEST_TESSERACTOCRIOS_LIBRARY_SEARCH_PATHS = "$(PODS_ROOT)/TesseractOCRiOS/TesseractOCR/lib" "$(PODS_ROOT)/TesseractOCRiOS/TesseractOCR/lib"
-PODS_TESSTEST_TESSERACTOCRIOS_OTHER_LDFLAGS = -weak_library /usr/lib/libstdc++.6.0.9.dylib -l"lept" -l"stdc++" -l"tesseract_all" -framework "Foundation" -framework "UIKit"
\ No newline at end of file
+PODS_TESSTEST_TESSERACTOCRIOS_OTHER_LDFLAGS = -l"lept" -l"stdc++" -l"tesseract_all" -framework "Foundation" -framework "UIKit"

This then notes (through over 200 warnings) that the libtesseract_all.a was built without bitcode, and needs to be rebuilt with it, but at least you can archive it.

Also, I experimented with changing the standard C++ library. This should not be changed.

Sample code runs in simulator and archives on 6.3.3 with this change.

**Comment by ws233** [comment] 2015-06-20 20:54
I confirm there are a lot of warning while building both test and example project for device in xCode 7. 
@tomjtobin, can you send a pull request to this repo or my own one, which is https://github.com/ws233/Tesseract-OCR-iOS, so I could test your fix?

**Comment by ghrom** [comment] 2015-07-18 07:29
I get the same issue in my iMtG project and I think the proper solution would be to include bitcode in compiled binaries using this method http://stackoverflow.com/questions/30722606/what-does-enable-bitcode-do-in-xcode-7

**Comment by ws233** [comment] 2015-07-19 08:29
So far I've failed to recompile dependant libraries with bitcode enabled. I try to check that the following compile flags (or some of their combination) from the link @ghrom has suggested could help us to fix an issue.

         -fembed-bitcode hi.c -S -emit-llvm

But there is a linker error with libz in xcode 7.0 beta. We should try xcode 7.0 beta 3. But I don't have enough time for that next few weeks. Can anyone simply run './build_dependencies.sh' and check if it can build dependencies under xcode 7.0 beta 3 or not?

Also I cannot apply those instructions from @tomjtobin to the current master version. It seems there is no -weak_library key anymore. It seems he uses quite old tesseract ios framework.

**Comment by ws233** [comment] 2015-07-24 14:04
I've rebuilt tesseract and all of its dependent libraries with botched support. Pls, refer to #202.
Since Xcode 7.0 is in beta yet, I think it's not necessary to merge this. I'm going to update libraries' binaries with the final Xcode and update this PR.
So far, pls, confirm that you don't have any warning related to bitcode and any other issues related with watchOS.
Thx!

**Comment by johnmillz** [comment] 2015-08-27 13:54
@ws233 This is causing me some other integration issues with a third party obfuscation tool. Is it a must to wait for Xcode 7 as it seems the c++ library doesn't need to be linked with iOS 7+ (which is what this project targets).

**Comment by ws233** [comment] 2015-08-27 14:00
> the c++ library doesn't need to be linked with iOS 7+.

@johnmillz, doesn't it?
What is exactly your issue?
You are able to use the code from my [fork] (https://github.com/ws233/Tesseract-OCR-iOS/tree/Bitcode), if you are not ready to wait until official release.

**Comment by ws233** [comment] 2015-10-11 08:17
Rebased and merged in #222.

**Comment by ws233** [comment] 2015-10-11 08:22
Closing.
Feel free to reopen the task if you have any further issues related to bitcode.

**Closed by ws233** 2015-10-11 08:22 UTC

**Comment by kwerle** [comment] 2016-01-20 23:08
I've just started trying to use tesseract and have run into this problem.  I'll probably disable bitcode for the moment, but I would like to avoid doing that.

What is the real solution to this issue?

**Comment by ws233** [comment] 2016-01-21 07:12
@kwerle, just use the most recent developer version.

**Comment by kwerle** [comment] 2016-01-21 15:35
Where would I find that?

**Comment by artemisia-absynthium** [comment] 2016-08-18 10:35
Hello, I've just created a brand new project, only added Tesseract dependency via Cocoapods (the project is still blank) and I'm having this issue. I'm using Xcode v7.3.1, Tesseract iOS v4.0.0 and my deployment target is iOS 7.1 (I only have a 7.1 real device atm so I have no choice since I want to use camera in my project).
I'll try the workarounds suggested hoping they'll do the trick but I wanted you to know that the issue is still there with these settings. :)

Steps to reproduce:

- Create a new iOS Swift project (I chose single view application)
- Change deployment target to 7.1
- `pod init`
- Add `pod 'TesseractOCRiOS', '4.0.0'` to `Podfile` and leave the rest as is
- `pod install`
- Try to build and run app on the device

**Comment by Manjunath-Ramesh** [comment] 2018-01-30 09:26
Try disabling bitcode for all the targets under Pods project, it worked for me.
![screen shot 2018-01-30 at 2 55 33 pm](https://user-images.githubusercontent.com/26483573/35558297-ada578e0-05cd-11e8-9352-0fb2b245acb0.png)

**Comment by hussainhspl** [comment] 2019-07-19 05:26
> Try disabling bitcode for all the targets under Pods project also, it worked for me.
> ![screen shot 2018-01-30 at 2 55 33 pm](https://user-images.githubusercontent.com/26483573/35558297-ada578e0-05cd-11e8-9352-0fb2b245acb0.png)

you will find this option in build setting tab
