### ISSUE TITLE
Wrong Line Break happens. 

### ISSUE THREAD

**Issue by ancheng1114** [gali8/Tesseract-OCR-iOS#262] opened 2016-05-10 09:00 UTC
I tried OCR , but there happens some line break.
I could not find solve issue.
Expected \n , but result was  \n\n.

**Comment by ws233** [comment] 2016-06-05 07:07
We are not responsible for Tesseract core.
For such questions, pls, refer the [upstream repository](https://github.com/tesseract-ocr/tesseract).
I'm closing an issue since it's not releated to the iOS wrapper.
Let me know, if you think the issue is caused by the wrapper.

**Closed by ws233** 2016-06-05 07:07 UTC
