### ISSUE TITLE
Linking problem with :head pod

### ISSUE THREAD

**Issue by BamX** [gali8/Tesseract-OCR-iOS#142] opened 2015-01-28 07:49 UTC
I've just update pod with latest version of plugin, so now I can't build my project because of linker failures
![2015-01-28 10-47-42 taggy xcworkspace](https://cloud.githubusercontent.com/assets/443972/5934083/1ca01804-a6db-11e4-950c-b5017da24e93.png)
I've made clean many times, clearing derived data and reinstall pods. Any suggestions?

**Comment by kevincon** [comment] 2015-01-28 08:02
What happens if you just create a brand new empty project and try to install the :head pod? If that builds okay, what happens if you add the minimum example code to do recognition (like init a G8Tesseract, give it the 0-9 sample image, and recognize on it)?

**Comment by BamX** [comment] 2015-01-28 08:13
It happens in absolutely new project too. Here a log:
![2015-01-28 11-11-39 temptescheck xcworkspace](https://cloud.githubusercontent.com/assets/443972/5934311/922deb84-a6de-11e4-9a96-09f8b473d7ec.png)
And Podfile content:
![2015-01-28 11-11-55 podfile](https://cloud.githubusercontent.com/assets/443972/5934315/9aedee5e-a6de-11e4-9599-74eec595a9f5.png)

**Comment by kevincon** [comment] 2015-01-28 08:28
I was able to reproduce the error you are getting.

I switched my Podfile to use this instead:

```
pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git'
```

(also using `#import <TesseractOCR/TesseractOCR.h>` for the import)

And it worked, so maybe there's something different about using `:head`?

**Comment by BamX** [comment] 2015-01-28 08:58
Are you sure that with that line you have latest version? (head) Please, try this version:
```
pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git', :commit => '92ef3d5'
```

**Comment by kevincon** [comment] 2015-01-29 07:01
That worked for me as well.

Here's the entire contents of my Podfile:

```
platform :ios, '7.0'

target 'BlahProject' do
pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git', :commit => '92ef3d5'
end
```

Each time I changed the Podfile I ran `pod install` which I believe is the correct way to re-configure the workspace after editing the Podfile, but let me know if you'd like me to try it another way.

**Comment by BamX** [comment] 2015-01-29 07:13
May be you should run ```pod update```.

**Comment by kevincon** [comment] 2015-01-29 07:42
Yeah it still works after `pod update`.

**Comment by kevincon** [comment] 2015-01-30 19:49
@ws233 do you have the issue @BamX describes above if you try creating a new project and using the head of the github repo for the CocoaPod?

**Comment by ws233** [comment] 2015-01-30 20:51
I do not use cocoa pods at all.
But let me check this issue on Monday.

>

-- 
---------------------------------------

Best regards,
Makankov Kirill

**Comment by ws233** [comment] 2015-02-06 08:06
Finally, I did check this issue.
I've create a new project, added a pod and use just a simple code 

      [[G8Tesseract alloc] init];

And there is a linking error:

      Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_G8Tesseract", referenced from:
      objc-class-ref in MasterViewController.o
      ld: symbol(s) not found for architecture x86_64
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

And I guess this is due to the cocoapod version. I do use an old release one (0.35.0). @BamX uses the same I guess. And only @kevincon has updated his pod executable to the last beta version.
Could it be a reason of the issue?

**Comment by kevincon** [comment] 2015-02-06 16:01
@ws233 what's your Podfile look like right now?

**Comment by ws233** [comment] 2015-02-06 16:09
pod 'TesseractOCRiOS', :head

**Comment by kevincon** [comment] 2015-02-06 16:14
Can you try replacing that with:

```
pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git', :commit => '92ef3d5'
```

and running `pod install`? Do you still get the linking errors then?

**Comment by ws233** [comment] 2015-02-06 17:13
That's ok. There are no linking errors, but only if I change import line, like you've already told above.
Also I did pod install verbose. And there is such line there:

    -> Installing TesseractOCRiOS 3.4.0 (was HEAD based on 3.4.0)

**Comment by kevincon** [comment] 2015-02-06 22:16
Thanks for looking into that, @ws233. @BamX since it works for both @ws233 and me, I think the linking errors might be an issue on your end.

**Comment by kevincon** [comment] 2015-02-06 22:21
Ah I think I understand what's going on, at least with why `:head` doesn't work. I'm not sure why it's not working for you, @BamX, when you use the github repo and the specific commit, but here's what CocoaPods mentions about using `:head`:

"Finally, instead of a version, you can specify the :head flag. This will use the pod’s latest version spec version, but force the download of the ‘bleeding edge’ version. Use this with caution, as the spec might not be compatible with the source material anymore."
Source: http://guides.cocoapods.org/using/the-podfile.html

Thus I think the issue is the fact that the CocoaPod spec in the repo has changed, so even though it's using the 'bleeding edge' version of the code from GitHub, it's still using the old spec from 3.4.0.

**Comment by kevincon** [comment] 2015-02-11 09:05
Using `:head` in the Podfile should work once we release version 4.0.0, but in the mean-time I've reverted the installation instruction in the Wiki to use the full GitHub repo URL for the development version of the CocoaPod: https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation

I'm going to close this issue for now.

**Closed by kevincon** 2015-02-11 09:05 UTC

**Comment by tuluigi** [comment] 2015-06-26 07:23
i have the same problem as @ws233  ； can @kevincon  tell me how to fix the problem ! thanks .

**Comment by kevincon** [comment] 2015-06-27 22:35
@tuluigi Can you open a new issue and describe your specific problem, mentioning what error message you are experiencing?

**Comment by ameenudheenirshad** [comment] 2015-11-30 09:24
@BamX  ur issue can be easily solved by add $(inherited)  to other linker flags in build settings. I too have the same issue and solved it.
