### ISSUE TITLE
Cocoapods 0.37.0 + Xcode 6.3 Warning: Multiple build commands for .../config_auto.h

### ISSUE THREAD

**Issue by yoiang** [gali8/Tesseract-OCR-iOS#176] opened 2015-05-08 15:16 UTC
Xcode is warning that config_auto.h is present twice in the Headers Build Phase and unfortunately cannot decide what to do with the fact that one config_auto.h comes from Tesseract and the other from Leptonica. Looking over the extended warning output (below) it becomes clear that both config_auto.h files end up at the same location when built, one presumably overwriting the other.

--verbose
warning: Multiple build commands for output file /Users/ian/Library/Developer/Xcode/DerivedData/Socratic-bayktzfmsafuxtbjfwcckwnwdjug/Build/Products/Debug-iphoneos/Pods-Socratic/TesseractOCR.framework/PrivateHeaders/config_auto.h

**Comment by ws233** [comment] 2015-07-26 19:25
@yoiang, are those files different?
As I think those files are auto generated by the configure utility and should contain some target specific macros used in all other library headers. Since the target is the same for Tesseract and Leptonica I believe those 2 headers should be similar. But can you confirm this for me?

**Comment by ws233** [comment] 2015-07-27 13:55
@yoiang,  I've tried xCode 7 with cocapods 0.38.2 version.
I couldn't reproduce your issue. Is it still reproduced in your case? Can you give more details?

**Comment by ws233** [comment] 2015-08-27 14:05
@kevincon, let's close this.

**Comment by Japspre** [comment] 2015-10-26 09:52
I have the same issue on cocoapods v0.39 with TesseractOCRiOS v4.0.0

![screen_shot_2015-10-26_at_10_51_14](https://cloud.githubusercontent.com/assets/6073131/10725878/9c5900d2-7bcf-11e5-8414-4860e867f03c.jpg)

**Comment by ws233** [comment] 2015-10-29 11:32
I cannot see this in the most recent commit.
Pls, use a developer version to fix this issue.

**Closed by ws233** 2015-10-29 11:32 UTC
Labels: bug

**Comment by Wolfenberg** [comment] 2016-02-26 11:04
When is this fix going live?

**Comment by ws233** [comment] 2016-02-26 11:05
@Wolfenberg it seems not being reprodecued in latest commit.

**Comment by Wolfenberg** [comment] 2016-02-26 11:06
@ws233 I'm using the latest 4.0.0 from CocoaPods (0.39.0) and see this warning

**Comment by ws233** [comment] 2016-02-26 11:20
@Wolfenberg, I'm talking about the last commit from the master of the repo.
You are talking about the last Cocoapod release.

**Comment by parthgargava** [comment] 2018-11-09 19:37
Has this issue been resolved? I am facing the same problem. 

Build failed:

Showing Recent Messages
:-1: Multiple commands produce '/Users/a608612/Library/Developer/Xcode/DerivedData/LoveInASnap-euozazwrksjcphdlmxledcbrjrmb/Build/Products/Debug-iphonesimulator/TesseractOCRiOS/TesseractOCR.framework/PrivateHeaders/config_auto.h':
1) Target 'TesseractOCRiOS' (project 'Pods') has copy command from '/Users/a608612/Desktop/OCR_Tutorial_Resources/LoveInASnap/Pods/TesseractOCRiOS/TesseractOCR/include/leptonica/config_auto.h' to '/Users/a608612/Library/Developer/Xcode/DerivedData/LoveInASnap-euozazwrksjcphdlmxledcbrjrmb/Build/Products/Debug-iphonesimulator/TesseractOCRiOS/TesseractOCR.framework/PrivateHeaders/config_auto.h'
2) Target 'TesseractOCRiOS' (project 'Pods') has copy command from '/Users/a608612/Desktop/OCR_Tutorial_Resources/LoveInASnap/Pods/TesseractOCRiOS/TesseractOCR/include/tesseract/config_auto.h' to '/Users/a608612/Library/Developer/Xcode/DerivedData/LoveInASnap-euozazwrksjcphdlmxledcbrjrmb/Build/Products/Debug-iphonesimulator/TesseractOCRiOS/TesseractOCR.framework/PrivateHeaders/config_auto.h'
